version: '2.4'

services:
  postgres:
    image: postgres:13
    container_name: trustcred-postgres
    environment:
      POSTGRES_DB: trustcred_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schemas:/docker-entrypoint-initdb.d

  redis:
    image: redis:6-alpine
    container_name: trustcred-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
